baseURL = "https://blog.no-trend.com/"
languageCode = "es-es"
title = "Agile Path"
theme = "bleak"

[params]
  # Warning Keys are case sensitives
  Subtitle = "Experimentos agiles !"
  description = "El maravilloso mundo agile !"
  cover = "/images/cover.jpg"

  # Google analytics
  googleAnalyticsUserID = "UA-xxxxxxxx-x"
  domainVerification = "xxxxxxxxxxxxxxxxxxxxx"
  disqus = "xxxxxxxxx"

  [params.author]
    firstName = "Victor"
    lastName = "Soria"
    gender = "(fe)?male"
    userName = "vjsoria"
    image = "//www.gravatar.com/avatar/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.png"
    website = "http://www.foo.com"
    twitter = "xxxxxxx"
    github = "xxxxxxx"
    facebook = "xxxxxxxxx"
    linkedin = "xxxxxxxxx"
    gplus = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    gravatarHash = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
